# These are supported funding model platforms

github: [naowal]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: pypi/django-100-days-of-codes
custom: # Replace with a single custom sponsorship URL
